# Generated by Django 4.2.3 on 2023-10-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='timezone',
        ),
        migrations.AlterField(
            model_name='attempthistory',
            name='played_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playedgame',
            name='played_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
