# Generated by Django 4.2.3 on 2023-09-06 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chess_content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playedgame',
            options={},
        ),
        migrations.RemoveField(
            model_name='playedgame',
            name='not_success',
        ),
    ]
