# Generated by Django 4.2.3 on 2023-09-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_content', '0002_alter_playedgame_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playedgame',
            name='gotCorrectRoundNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
