# Generated by Django 4.2.3 on 2023-09-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_content', '0004_playedgame_chosendifficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='playedgame',
            name='game_is_on',
            field=models.BooleanField(default=False),
        ),
    ]
