# Generated by Django 4.2.3 on 2023-09-18 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chess_content', '0005_playedgame_game_is_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playedgame',
            name='game_is_on',
        ),
    ]
