# Generated by Django 4.2.3 on 2023-09-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_content', '0006_remove_playedgame_game_is_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='playedgame',
            name='game_is_on',
            field=models.BooleanField(default=False),
        ),
    ]
