# Generated by Django 4.2.3 on 2023-09-18 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_content', '0007_playedgame_game_is_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='playedgame',
            name='fen_str',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
