# Generated by Django 4.2.3 on 2023-09-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_content', '0008_playedgame_fen_str'),
    ]

    operations = [
        migrations.AddField(
            model_name='playedgame',
            name='error_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
