# Generated by Django 4.2.3 on 2023-09-21 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_content', '0009_playedgame_error_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='playedgame',
            name='round_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
