# Generated by Django 4.2.3 on 2023-10-04 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chess_content', '0010_playedgame_round_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fen_string', models.CharField(max_length=100)),
                ('game_is_on', models.BooleanField(default=False)),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('error_count', models.IntegerField(blank=True, null=True)),
                ('chosenDifficulty', models.CharField(blank=True, max_length=100)),
                ('played_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='chess_content.playedgame')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
