# Generated by Django 4.2.3 on 2023-10-04 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chess_content', '0011_attempthistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attempthistory',
            old_name='error_count',
            new_name='round_number',
        ),
    ]
