# Generated by Django 4.2.3 on 2023-10-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_content', '0012_rename_error_count_attempthistory_round_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempthistory',
            name='round_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
