# Generated by Django 4.2.3 on 2023-10-04 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chess_content', '0013_attempthistory_round_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attempthistory',
            old_name='round_number',
            new_name='total_round_number',
        ),
    ]
