# Generated by Django 4.2.3 on 2023-10-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_content', '0014_rename_round_number_attempthistory_total_round_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempthistory',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
